<?php

/**
 * @file
 * bootstrap5custom theme file.
 */


/**
 * Implements hook_preprocess_links().
 */
function bootstrap5custom_preprocess_links(&$variables) {
  $variables['links']['node-readmore']['link']['#options']['attributes']['class'][] = 'btn btn-sm btn-secondary';
  $variables['links']['comment-comments']['link']['#options']['attributes']['class'][] = 'btn btn-sm btn-secondary';
  $variables['links']['comment-add']['link']['#options']['attributes']['class'][] = 'btn btn-sm btn-primary';
  $variables['links']['comment-delete']['link']['#options']['attributes']['class'][] = 'btn btn-sm btn-secondary';
  $variables['links']['comment-edit']['link']['#options']['attributes']['class'][] = 'btn btn-sm btn-secondary';
  $variables['links']['comment-reply']['link']['#options']['attributes']['class'][] = 'btn btn-sm btn-secondary';
  /* Book */
  $variables['links']['book_printer']['link']['#options']['attributes']['class'][] = 'btn btn-sm btn-secondary';
  $variables['links']['book_add_child']['link']['#options']['attributes']['class'][] = 'btn btn-sm btn-secondary';
}